{
 "title": "LOGISTPULSE Operations Overview",
 "tags": [
  "logistpulse",
  "operations"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(logistpulse_http_requests_total[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "p95 API latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(logistpulse_http_request_duration_seconds_bucket[5m])) by (le,service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Container CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"logistpulse.*\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}